### PR TITLE
API for rfai request summary

### PR DESCRIPTION
**Pull request by prashantramangupta**

### CODE REVIEW

**Review by keshrisohit — COMMENTED** [review]
add alembic for tables creation

**Review by ksridharbabuus — APPROVED** [review]
Approved. Need to modify the Queries based on the Status Computations.

**Review by keshrisohit — COMMENTED** [review]
we should write unit test cases as well along with code, not  as a separate task

**Comment by prashantramangupta** [comment]
> we should write unit test cases as well along with code, not as a separate task

I have checked in the very basic version. Code is not completed. Will add with final PR of my task.

**Pull request merged**
